# Generated by Django 4.0.3 on 2022-03-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('failedAttempts', models.IntegerField()),
                ('timeFailed', models.CharField(max_length=100)),
            ],
        ),
    ]
