# Generated by Django 4.0.3 on 2022-03-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='timeFailed',
            new_name='lastLoginTime',
        ),
    ]
